apiVersion: v1
kind: Pod
metadata:
  name: cluster-pod
  labels:
        project: roboshop
        component: frontend
        environment: dev
spec:
    containers:
      - name: nginx
        image: nginx