apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    type: LoadBalancer
    project: roboshop
    component: frontend
    environment: dev
    purpose: load-balancer

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80     