apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    project: roboshop
    component: container
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
    - name: almalinux
      image: almalinux:9
      command: ["sleep","1000"]