apiVersion: v1
kind: Pod
metadata:
  name: resource
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - ContainerPort: 80
      resources:
        requests:
          memory: "60Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "120m"