apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  labels:
    project: roboshop
    component: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
      envfrom:
        - SecretRef:
            name: pod-secret